### ISSUE TITLE
Question regarding the latency of the intersection unit

### ISSUE THREAD

**Issue by leonhsi** [ubc-aamodt-group/ray-intersection-predictor#1]
Amazing work but I have a few questions for this project.

How do you estimate the latency of the intersection unit in the ray predictor in src/gpgpu-sim/ray-predictor.cc? 
That means how did you benchmark the real intersection unit in NVIDIA RT core? 
Did you use some micro benchmark to achieve this estimation?

Thanks, 
looking forwards to your reply.

**Comment by lucylufei** [comment]
Hi Leon, 

Thanks for your interest in our work!

Since NVIDIA does not reveal details of their implementation, we estimate the intersection unit latency based on the [T&I engine](https://my.eng.utah.edu/~cs6958/papers/HWRT-seminar/a160-nah.pdf). As I also mentioned in my email, we did not microbenchmark the NVIDIA RT Core for the precise number of cycles / pipeline stages. 

The latencies in [ray-predictor.cc](../tree/main/src/gpgpu-sim/ray-predictor.cc) are modelling access latency to the predictor table and not the intersection computation itself. The ray-box and ray-triangle intersection test latencies are modelled in the rt_unit in [shader.cc](../tree/main/src/gpgpu-sim/shader.cc). These latencies can all be modified in the [configuration file](../tree/main/configs/tested-cfgs/MOBILE/gpgpusim.config).

Please let me know if you have any further questions 😊
