### ISSUE TITLE
Understanding the Role of Warm-Up Kernels and the '-w' Flag in Code

### ISSUE THREAD

**Issue by quanzw99** [ubc-aamodt-group/ray-intersection-predictor#3]
Hi Team,

The '-w' denotes the number of warm-up kernels, and I'm quite confused about the role of the warm-up kernels. Their computations don't seem to differ from those in the measurement. Could you please provide me with some clues?

**Comment by lucylufei** [comment]
Hi there! As far as I remember, the `-w` parameter controls the number of warm-up rays to trace. The warm-up happens in the first kernel and the measurement happens in the second kernel. The kernels are the same, but running them separately helps us track GPGPU-Sim statistics separately for warm-up versus actual results. The statistics of the first kernel can be ignored since this is considered the warm-up kernel. 

Hope this helps!

**Comment by quanzw99** [comment]
Thanks for the quick response! The information is helpful!
